# docker compose  --- 노출포트 16379 로 함
version: '3'
services:
  redis:
    container_name: redis
    image: 'redis:7'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=
    ports:
      - '16379:6379'
    networks:
      - redis
    restart: always
    command: redis-server --appendonly yes --appendfsync everysec
    user: "${USER_ID}:${GROUP_ID}"
networks:
  redis:
    driver: bridge
