version: '3'
services:
  app:
    build: .
    restart: on-failure
    container_name: chatbot
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./schedule_log:/home/cucuridas/chatbot_tg/schedule_log
